    - name: Start the App
      ansible.builtin.shell: |
            cd /root/flask_app/
            export FLASK_APP=app
            export FLASK_ENV=development
            nohup flask run --host=0.0.0.0 &