---
# tasks file for python
    - name: Install OS packages
      apt: 
        name: "{{ item }}"
        state: latest
      with_items: 
        - python3
        - python3-setuptools
        - python3-dev
        - build-essential
        - python3-pip
        - python3-flask
        - python3-psycopg2
        - libpq-dev
    
    - name: Disalbe this for container
      shell: python3 -m pip config set global.break-system-packages true